name: 'pocketgull_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'pocketgull_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  pocketgull_dbt:
    staging:
      +materialized: view
      +dataset: pocketgull_staging
    marts:
      +materialized: table
      +dataset: pocketgull_analytics
    ml:
      +materialized: model
      +dataset: pocketgull_analytics
