[pytest]
testpaths = .
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore:.*httpx.*:DeprecationWarning
    ignore:.*starlette.*
    ignore:.*Using `httpx` with `starlette.testclient`.*
