run:
  timeout: 5m
  concurrency: 4
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gofmt
    - misspell
    - unconvert
    - prealloc
    - revive

linters-settings:
  govet:
    disable:
      - fieldalignment
      - shadow
  gosec:
    severity: medium
    confidence: medium
  revive:
    rules:
      - name: exported
        disabled: false
      - name: blank-imports
        disabled: false
      - name: context-as-argument
        disabled: false
      - name: error-return
        disabled: false
      - name: error-strings
        disabled: false
      - name: error-naming
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
