import { Component, ChangeDetectionStrategy, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GaapTribalStewardshipService, IGaapFunctionalExpense } from '../../services/gaap-tribal-stewardship.service';

@Component({
  selector: 'app-gaap-tribal-stewardship-card',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="bg-zinc-950 border border-zinc-800 rounded-2xl p-6 sm:p-8 text-zinc-100 shadow-2xl space-y-6">
      
      <!-- Top Header -->
      <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-zinc-800 pb-6">
        <div>
          <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-400 text-xs font-mono font-semibold uppercase tracking-wider mb-2">
            <span>⚖️ US GAAP FASB ASC 958 Financial Stewardship</span>
          </div>
          <h3 class="text-xl sm:text-2xl font-extrabold text-zinc-50 tracking-tight">
            Functional Revenue Allocation &amp; Tribal Health Goals
          </h3>
          <p class="text-xs sm:text-sm text-zinc-400 mt-1 max-w-3xl leading-relaxed">
            Every dollar generated by PocketGull is audited under strict US GAAP Not-for-Profit functional accounting covenants (ASC 958-205) and CARE/OCAP Indigenous Data Sovereignty standards.
          </p>
        </div>

        <div class="shrink-0 flex items-center gap-2">
          <button 
            type="button"
            (click)="downloadGaapCsv()"
            class="px-3.5 py-2 bg-zinc-900 hover:bg-zinc-800 border border-zinc-700 text-xs font-mono font-bold uppercase tracking-wider rounded-lg transition text-zinc-200 hover:text-white flex items-center gap-2 cursor-pointer">
            <span>📥 Export GAAP Statement (CSV)</span>
          </button>
        </div>
      </div>

      <!-- Key Financial Ratios Spotlight Grid -->
      <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div class="bg-zinc-900/90 border border-emerald-500/40 p-4 rounded-xl">
          <div class="text-[11px] font-mono text-zinc-400 uppercase tracking-wider">Programmatic Direct Benefit</div>
          <div class="text-2xl font-black text-emerald-400 mt-1">85.0%</div>
          <p class="text-xs text-zinc-400 mt-1">Directly allocated to Tribal Clinics, Patient Data Dividends, and Open Source Codex.</p>
        </div>

        <div class="bg-zinc-900/90 border border-sky-500/40 p-4 rounded-xl">
          <div class="text-[11px] font-mono text-zinc-400 uppercase tracking-wider">Technology &amp; Security</div>
          <div class="text-2xl font-black text-sky-400 mt-1">10.0%</div>
          <p class="text-xs text-zinc-400 mt-1">On-device Gemma 4 optimization, zero-trust WASM compilers, and post-quantum ZKP.</p>
        </div>

        <div class="bg-zinc-900/90 border border-amber-500/40 p-4 rounded-xl">
          <div class="text-[11px] font-mono text-zinc-400 uppercase tracking-wider">Governance &amp; Statutory Audit</div>
          <div class="text-2xl font-black text-amber-400 mt-1">5.0%</div>
          <p class="text-xs text-zinc-400 mt-1">Independent CPA audits, dual-custody treasury multi-signature controls, and legal.</p>
        </div>
      </div>

      <!-- Functional Expense Breakdown Cards -->
      <div class="space-y-3">
        <div class="text-xs font-mono text-zinc-400 uppercase tracking-wider">Statement of Functional Expenses (GAAP ASC 958):</div>
        
        @for (item of gaapService.statement().functionalExpenses; track item.categoryName) {
          <div class="bg-zinc-900/60 border border-zinc-800 rounded-xl p-4 space-y-2 hover:border-zinc-700 transition">
            <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
              <div class="flex items-center gap-2">
                <span class="font-bold text-sm text-zinc-100">{{ item.categoryName }}</span>
                <span class="text-[10px] font-mono font-bold px-2 py-0.5 rounded"
                      [class.bg-emerald-500/20]="item.gaapClassification === 'PROGRAM_SERVICES'"
                      [class.text-emerald-300]="item.gaapClassification === 'PROGRAM_SERVICES'"
                      [class.bg-sky-500/20]="item.gaapClassification === 'SYSTEMS_INFRASTRUCTURE'"
                      [class.text-sky-300]="item.gaapClassification === 'SYSTEMS_INFRASTRUCTURE'"
                      [class.bg-amber-500/20]="item.gaapClassification === 'MANAGEMENT_GENERAL'"
                      [class.text-amber-300]="item.gaapClassification === 'MANAGEMENT_GENERAL'">
                  {{ item.gaapClassification }}
                </span>
              </div>
              <div class="font-mono font-extrabold text-sm text-zinc-100">{{ item.percentage }}% Allocation</div>
            </div>

            <!-- Progress Bar -->
            <div class="w-full bg-zinc-800 rounded-full h-2 overflow-hidden">
              <div class="h-full rounded-full transition-all duration-500"
                   [style.width.%]="item.percentage"
                   [class.bg-emerald-400]="item.gaapClassification === 'PROGRAM_SERVICES'"
                   [class.bg-sky-400]="item.gaapClassification === 'SYSTEMS_INFRASTRUCTURE'"
                   [class.bg-amber-400]="item.gaapClassification === 'MANAGEMENT_GENERAL'">
              </div>
            </div>

            <p class="text-xs text-zinc-300 leading-relaxed">{{ item.tribalGoalDescription }}</p>

            <div class="flex flex-wrap items-center gap-2 pt-1">
              <span class="text-[10px] font-mono text-zinc-500">Covenants:</span>
              @for (std of item.governingStandards; track std) {
                <span class="text-[10px] font-mono px-2 py-0.5 rounded bg-zinc-800 text-zinc-400 border border-zinc-700">
                  {{ std }}
                </span>
              }
            </div>
          </div>
        }
      </div>

      <!-- CPA Audit Attestation & Dual Custody Footer -->
      <div class="bg-zinc-900 border border-zinc-800 rounded-xl p-4 sm:p-5 flex flex-col md:flex-row items-start md:items-center justify-between gap-4 text-xs">
        <div class="space-y-1">
          <div class="font-bold text-zinc-200 flex items-center gap-2">
            <span>🛡️ CPA Audit Attestation:</span>
            <span class="text-emerald-400 font-mono">Unmodified Clean Opinion</span>
          </div>
          <p class="text-zinc-400 text-[11px] max-w-2xl">
            {{ gaapService.statement().auditAttestation.opinion }}
          </p>
        </div>

        <div class="shrink-0 space-y-1 font-mono text-[10px] text-zinc-400 bg-zinc-950 p-2.5 rounded border border-zinc-800">
          <div class="text-teal-400 font-bold">Dual-Custody Multi-Sig Signatures:</div>
          @for (sig of gaapService.statement().auditAttestation.dualCustodySignatures; track sig) {
            <div>✓ {{ sig }}</div>
          }
        </div>
      </div>

    </div>
  `
})
export class GaapTribalStewardshipCardComponent {
  gaapService = inject(GaapTribalStewardshipService);

  downloadGaapCsv(): void {
    const csvContent = this.gaapService.generateGaapCsvExport();
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PocketGull_GAAP_Tribal_Stewardship_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }
}
