import { Component, inject, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ConsentService } from '../../services/consent.service';

/**
 * First-run informed consent modal.
 * Explains data handling, AI processing, and local encryption
 * before any patient data is entered.
 *
 * @see ACM Code of Ethics §1.6 — Respect Privacy
 */
@Component({
    selector: 'app-consent-modal',
    standalone: true,
    imports: [CommonModule],
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
    <div class="fixed inset-0 z-[9999] flex items-center justify-center p-3 sm:p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-300"
         role="dialog" aria-modal="true" aria-labelledby="consent-title">
      <div class="bg-white dark:bg-zinc-900 rounded-3xl shadow-2xl border border-gray-200 dark:border-zinc-700 max-w-lg w-full max-h-[90vh] flex flex-col overflow-hidden animate-in zoom-in-95 duration-200">

        <!-- Header (Pinned) -->
        <div class="p-4 sm:p-6 pb-3 border-b border-gray-100 dark:border-zinc-800 shrink-0">
          <div class="flex items-center gap-3">
            <div class="w-10 h-10 rounded-2xl bg-gradient-to-br from-emerald-500 to-green-600 flex items-center justify-center shadow-lg shadow-emerald-500/20 shrink-0">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
              </svg>
            </div>
            <div>
              <h2 id="consent-title" class="text-base sm:text-lg font-bold text-gray-900 dark:text-zinc-100">Data Privacy & AI Disclosure</h2>
              <p class="text-xs text-gray-500 dark:text-zinc-400">Please review before continuing</p>
            </div>
          </div>
        </div>

        <!-- Content (Scrollable) -->
        <div class="p-4 sm:p-6 py-3 space-y-4 text-xs sm:text-sm text-gray-700 dark:text-zinc-300 leading-relaxed overflow-y-auto overscroll-contain">

          <!-- Section 1: Local Storage -->
          <div class="flex gap-3">
            <div class="w-8 h-8 rounded-xl bg-blue-50 dark:bg-blue-950/30 flex items-center justify-center shrink-0 mt-0.5">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-blue-600 dark:text-blue-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>
              </svg>
            </div>
            <div>
              <h3 class="font-bold text-gray-900 dark:text-zinc-100 mb-0.5">Your Data Stays on Your Device</h3>
              <p class="text-xs text-gray-600 dark:text-zinc-400">Patient information is stored <strong>locally</strong> on this device using AES-256 encryption. We do not maintain a server-side database of patient records.</p>
            </div>
          </div>

          <!-- Section 2: AI Processing -->
          <div class="flex gap-3">
            <div class="w-8 h-8 rounded-xl bg-violet-50 dark:bg-violet-950/30 flex items-center justify-center shrink-0 mt-0.5">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-violet-600 dark:text-violet-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M12 2a4 4 0 0 0-4 4c0 2 1 3.5 2 4.5L12 12l2-1.5c1-1 2-2.5 2-4.5a4 4 0 0 0-4-4z"/><path d="M12 12v10"/><path d="M8 22h8"/>
              </svg>
            </div>
            <div>
              <h3 class="font-bold text-gray-900 dark:text-zinc-100 mb-0.5">AI-Powered Analysis</h3>
              <p class="text-xs text-gray-600 dark:text-zinc-400">Clinical analyses are generated by <strong>Google Gemini</strong>. When you run an analysis, patient data is transmitted to Google's API for processing.</p>
            </div>
          </div>

          <!-- Section 3: AI Limitations -->
          <div class="flex gap-3">
            <div class="w-8 h-8 rounded-xl bg-amber-50 dark:bg-amber-950/30 flex items-center justify-center shrink-0 mt-0.5">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-amber-600 dark:text-amber-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/>
              </svg>
            </div>
            <div>
              <h3 class="font-bold text-gray-900 dark:text-zinc-100 mb-0.5">Not a Medical Device</h3>
              <p class="text-xs text-gray-600 dark:text-zinc-400">Pocket Gull is a <strong>clinical decision-support tool</strong>, not a diagnostic instrument. Always verify recommendations with a licensed clinician.</p>
            </div>
          </div>

          <!-- Section 4: What we DON'T do -->
          <div class="flex gap-3">
            <div class="w-8 h-8 rounded-xl bg-emerald-50 dark:bg-emerald-950/30 flex items-center justify-center shrink-0 mt-0.5">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-emerald-600 dark:text-emerald-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <polyline points="20 6 9 17 4 12"/>
              </svg>
            </div>
            <div>
              <h3 class="font-bold text-gray-900 dark:text-zinc-100 mb-0.5">Our Commitments</h3>
              <ul class="space-y-1 text-xs text-gray-600 dark:text-zinc-400">
                <li class="flex items-center gap-1.5">
                  <span class="text-emerald-500 font-bold">✓</span> No patient data is sold or shared
                </li>
                <li class="flex items-center gap-1.5">
                  <span class="text-emerald-500 font-bold">✓</span> No behavioral tracking or advertising profiles
                </li>
                <li class="flex items-center gap-1.5">
                  <span class="text-emerald-500 font-bold">✓</span> 1-Click transient patient state purge
                </li>
              </ul>
            </div>
          </div>
        </div>

        <!-- Footer (Pinned - Fitts's Law 48px Touch Target) -->
        <div class="p-4 sm:p-6 pt-3 border-t border-gray-100 dark:border-zinc-800 space-y-2 shrink-0 bg-gray-50/50 dark:bg-zinc-950/50">
          <button (click)="consent.acceptConsent()"
                  class="w-full min-h-[48px] py-3 px-4 bg-gradient-to-r from-emerald-600 to-green-600 hover:from-emerald-500 hover:to-green-500 text-white font-bold rounded-2xl shadow-lg shadow-emerald-500/20 active:scale-[0.98] transition-all duration-200 text-xs uppercase tracking-wider cursor-pointer flex items-center justify-center gap-2">
            <span>🛡️ I Understand — Continue</span>
          </button>
          <p class="text-[11px] text-center text-gray-400 dark:text-zinc-500">
            By continuing, you acknowledge this clinical disclosure.
          </p>
        </div>
      </div>
    </div>
    `,
})
export class ConsentModalComponent {
    consent = inject(ConsentService);
}

