name: pocketgull_flutter
description: "Pocket-Gull Minimal Hybrid Shell & Native Device Bridge"
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '^3.12.2'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1
  webview_flutter_web: ^0.2.3+4
  local_auth: ^3.0.2
  flutter_secure_storage: ^11.0.0
  connectivity_plus: ^7.3.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
