[package]
name = "pocketgull-wasm"
version = "0.1.0"
edition = "2021"
authors = ["Phil Gear <dpo@pocketgull.app>"]
description = "WebAssembly Edge Module for client-side browser & edge-worker HIPAA confidential computing."
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pocketgull-core = { path = "../pocketgull-core" }
