apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pocketgull-production

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - network-policy.yaml
  - gateway.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: pocketgull-clinical-intelligence
