apiVersion: v1
kind: Secret
metadata:
  name: pocketgull-secrets
  labels:
    {{- include "pocketgull.labels" . | nindent 4 }}
type: Opaque
stringData:
  GEMINI_API_KEY: "development_placeholder"
  SECRET_MANAGER_KEY: "development_placeholder"
