apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
    {{- include "pocketgull.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      securityContext:
        {{- toYaml .Values.web.securityContext | nindent 8 }}
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: pocketgull-config
            - secretRef:
                name: pocketgull-secrets
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          volumeMounts:
            - name: tmp-vol
              mountPath: /tmp
      volumes:
        - name: tmp-vol
          emptyDir: {}
