apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web
    {{- include "pocketgull.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
  selector:
    app: web
