import { Component, inject, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ConsentService } from '../services/consent.service';

/**
 * First-run informed consent modal.
 * Explains data handling, AI processing, and local encryption
 * before any patient data is entered.
 *
 * @see ACM Code of Ethics §1.6 — Respect Privacy
 */
@Component({
    selector: 'app-consent-modal',
    standalone: true,
    imports: [CommonModule],
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
    <div class="fixed inset-0 z-[9999] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-300"
         role="dialog" aria-modal="true" aria-labelledby="consent-title">
      <div class="bg-white dark:bg-zinc-900 rounded-2xl shadow-2xl border border-gray-200 dark:border-zinc-700 max-w-lg w-full max-h-[85vh] overflow-y-auto">

        <!-- Header -->
        <div class="p-6 pb-4 border-b border-gray-100 dark:border-zinc-800">
          <div class="flex items-center gap-3 mb-2">
            <div class="w-10 h-10 rounded-xl bg-gradient-to-br from-emerald-500 to-green-600 flex items-center justify-center shadow-lg shadow-emerald-500/20">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
              </svg>
            </div>
            <div>
              <h2 id="consent-title" class="text-lg font-bold text-gray-900 dark:text-zinc-100">Data Privacy & AI Disclosure</h2>
              <p class="text-xs text-gray-500 dark:text-zinc-400">Please review before continuing</p>
            </div>
          </div>
        </div>

        <!-- Content -->
        <div class="p-6 space-y-5 text-sm text-gray-700 dark:text-zinc-300 leading-relaxed">

          <!-- Section 1: Local Storage -->
          <div class="flex gap-3">
            <div class="w-8 h-8 rounded-lg bg-blue-50 dark:bg-blue-950/30 flex items-center justify-center shrink-0 mt-0.5">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-blue-600 dark:text-blue-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>
              </svg>
            </div>
            <div>
              <h3 class="font-semibold text-gray-900 dark:text-zinc-100 mb-1">Your Data Stays on Your Device</h3>
              <p>Patient information is stored <strong>locally</strong> on this device using AES-256 encryption. We do not maintain a server-side database of patient records.</p>
            </div>
          </div>

          <!-- Section 2: AI Processing -->
          <div class="flex gap-3">
            <div class="w-8 h-8 rounded-lg bg-violet-50 dark:bg-violet-950/30 flex items-center justify-center shrink-0 mt-0.5">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-violet-600 dark:text-violet-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M12 2a4 4 0 0 0-4 4c0 2 1 3.5 2 4.5L12 12l2-1.5c1-1 2-2.5 2-4.5a4 4 0 0 0-4-4z"/><path d="M12 12v10"/><path d="M8 22h8"/>
              </svg>
            </div>
            <div>
              <h3 class="font-semibold text-gray-900 dark:text-zinc-100 mb-1">AI-Powered Analysis</h3>
              <p>Clinical analyses are generated by <strong>Google Gemini</strong>. When you run an analysis, patient data is transmitted to Google's API for processing. Google's data processing terms apply to these transmissions.</p>
            </div>
          </div>

          <!-- Section 3: AI Limitations -->
          <div class="flex gap-3">
            <div class="w-8 h-8 rounded-lg bg-amber-50 dark:bg-amber-950/30 flex items-center justify-center shrink-0 mt-0.5">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-amber-600 dark:text-amber-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/>
              </svg>
            </div>
            <div>
              <h3 class="font-semibold text-gray-900 dark:text-zinc-100 mb-1">Not a Medical Device</h3>
              <p>Pocket Gull is a <strong>clinical decision-support tool</strong>, not a diagnostic instrument. AI outputs may contain errors and have <strong>not been verified by a licensed clinician</strong>. Always verify recommendations with your care team.</p>
            </div>
          </div>

          <!-- Section 4: What we DON'T do -->
          <div class="flex gap-3">
            <div class="w-8 h-8 rounded-lg bg-emerald-50 dark:bg-emerald-950/30 flex items-center justify-center shrink-0 mt-0.5">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-emerald-600 dark:text-emerald-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <polyline points="20 6 9 17 4 12"/>
              </svg>
            </div>
            <div>
              <h3 class="font-semibold text-gray-900 dark:text-zinc-100 mb-1">Our Commitments</h3>
              <ul class="space-y-1 mt-1.5 text-gray-600 dark:text-zinc-400">
                <li class="flex items-start gap-1.5">
                  <span class="text-emerald-500 mt-0.5">&#10003;</span> No patient data is sold or shared with third parties
                </li>
                <li class="flex items-start gap-1.5">
                  <span class="text-emerald-500 mt-0.5">&#10003;</span> No behavioral tracking or advertising profiles
                </li>
                <li class="flex items-start gap-1.5">
                  <span class="text-emerald-500 mt-0.5">&#10003;</span> You can delete all local data at any time
                </li>
                <li class="flex items-start gap-1.5">
                  <span class="text-emerald-500 mt-0.5">&#10003;</span> Open-source codebase for full transparency
                </li>
              </ul>
            </div>
          </div>
        </div>

        <!-- Footer -->
        <div class="p-6 pt-4 border-t border-gray-100 dark:border-zinc-800 space-y-3">
          <button (click)="consent.acceptConsent()"
                  class="w-full py-3 px-4 bg-gradient-to-r from-emerald-600 to-green-600 hover:from-emerald-500 hover:to-green-500 text-white font-semibold rounded-xl shadow-lg shadow-emerald-500/20 transition-all duration-200 active:scale-[0.98] text-sm">
            I Understand — Continue
          </button>
          <p class="text-[12px] text-center text-gray-400 dark:text-zinc-500">
            By continuing, you acknowledge this disclosure. Review our
            <a href="/privacy-policy.html" target="_blank" class="underline hover:text-gray-600 dark:hover:text-zinc-300 transition-colors">Privacy Policy</a> and
            <a href="/terms-of-service.html" target="_blank" class="underline hover:text-gray-600 dark:hover:text-zinc-300 transition-colors">Terms of Service</a>
            for full details.
          </p>
        </div>
      </div>
    </div>
    `,
})
export class ConsentModalComponent {
    consent = inject(ConsentService);
}
