# PocketGull Nero Marquina Kitty Theme
background #0d0d11
foreground #f8fafc
cursor #eab308
selection_background #eab3082c
color0 #0d0d11
color1 #ef4444
color2 #10b981
color3 #eab308
color4 #38bdf8
color5 #a855f7
color6 #14b8a6
color7 #f8fafc
color8 #64748b
color9 #f87171
color10 #34d399
color11 #fde047
color12 #60a5fa
color13 #c084fc
color14 #2dd4bf
color15 #ffffff
