# PocketGull Darkfield Electron Kitty Theme
background #0f1115
foreground #e4e4e7
cursor #facc15
selection_background #facc1533
color0 #0f1115
color1 #ef4444
color2 #facc15
color3 #cbd5e1
color4 #38bdf8
color5 #fb923c
color6 #f97316
color7 #e4e4e7
color8 #71717a
color9 #f87171
color10 #facc15
color11 #cbd5e1
color12 #38bdf8
color13 #fb923c
color14 #f97316
color15 #ffffff
