# PocketGull Curie Luminescence Kitty Theme
background #050b08
foreground #d1fae5
cursor #10b981
selection_background #132d20
color0 #0b1610
color1 #f87171
color2 #10b981
color3 #fcd34d
color4 #2dd4bf
color5 #a7f3d0
color6 #34d399
color7 #ecfdf5
color8 #1e3a2b
color9 #fca5a5
color10 #34d399
color11 #fde68a
color12 #5eead4
color13 #d1fae5
color14 #6ee7b7
color15 #ffffff