import json
import os

notebook = {
  "cells": [
    {
      "cell_type": "markdown",
      "id": "v5-header-0",
      "metadata": {},
      "source": [
        "# RSNA Knee 2026 — Multi-Plane 2.5D MIL with Soft-Weighted Asymmetric Loss (v5.0.0)\n",
        "\n",
        "### Key v5 Improvements:\n",
        "1. **Continuous Soft-Weighted Asymmetric Loss (ASL)**: Retains all 4,407 studies throughout all training epochs with sample weights ($w_{\\text{gold}} = 1.00, w_{\\text{weak}} = 0.40$). Focuses gradients on hard positives ($\\gamma_- = 4.0, \\gamma_+ = 1.0, \\text{clip} = 0.05$).\n",
        "2. **Bayesian Co-Occurrence Prior Smoothing**: Calibrates multi-label abnormality correlations across joint ligaments and cartilage.\n",
        "3. **Cosine Annealing LR Scheduler**: Warmup from $1e-5$ to $3e-4$, decaying smoothly to $1e-6$.\n",
        "4. **Out-of-Fold (OOF) Prediction Tracking**: Saves calibrated validation probabilities and generates out-of-fold calibration curves.\n",
        "5. **Zero-Crash Rule Conformance**: Immediate disk outputs, ASCII status prints, and explicit memory cleanup."
      ]
    },
    {
      "cell_type": "code",
      "id": "v5-imports-1",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "import os\n",
        "import gc\n",
        "import sys\n",
        "import time\n",
        "import math\n",
        "import random\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "from typing import Dict, List, Tuple, Optional, Any\n",
        "from sklearn.metrics import roc_auc_score\n",
        "from sklearn.model_selection import KFold\n",
        "\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "import torchvision\n",
        "\n",
        "try:\n",
        "    import pydicom\n",
        "    HAS_PYDICOM = True\n",
        "except ImportError:\n",
        "    HAS_PYDICOM = False\n",
        "    print('[WARN] pydicom not installed')\n",
        "\n",
        "VERSION = '5.0.0'\n",
        "TARGET_COLS = [\n",
        "    'ACL', 'MCL', 'Medial Meniscus', 'Lateral Meniscus',\n",
        "    'Medial OA', 'Lateral OA', 'PF OA', 'Effusion',\n",
        "    'Synovitis', \"Baker's\", 'Contusion', 'Fracture'\n",
        "]\n",
        "\n",
        "POPULATION_PRIORS = np.array([\n",
        "    0.18, 0.12, 0.28, 0.22, 0.35, 0.25, 0.20, 0.42,\n",
        "    0.30, 0.15, 0.10, 0.04\n",
        "], dtype=np.float32)\n",
        "\n",
        "def seed_everything(seed=42):\n",
        "    random.seed(seed)\n",
        "    os.environ['PYTHONHASHSEED'] = str(seed)\n",
        "    np.random.seed(seed)\n",
        "    torch.manual_seed(seed)\n",
        "    torch.cuda.manual_seed(seed)\n",
        "    torch.backends.cudnn.deterministic = True\n",
        "\n",
        "def get_safe_device() -> torch.device:\n",
        "    if torch.cuda.is_available():\n",
        "        try:\n",
        "            cap = torch.cuda.get_device_capability()\n",
        "            if cap[0] >= 7:\n",
        "                print(f'[OK] Using CUDA GPU: {torch.cuda.get_device_name(0)} (sm_{cap[0]}{cap[1]})')\n",
        "                return torch.device('cuda')\n",
        "            else:\n",
        "                print(f'[WARN] GPU capability sm_{cap[0]}{cap[1]} < sm_70. Falling back to CPU.')\n",
        "                return torch.device('cpu')\n",
        "        except Exception as ex:\n",
        "            print(f'[WARN] CUDA device check failed: {ex}. Using CPU.')\n",
        "            return torch.device('cpu')\n",
        "    return torch.device('cpu')\n",
        "\n",
        "seed_everything()\n",
        "device = get_safe_device()\n",
        "print(f'[OK] RSNA Knee Training Pipeline (v{VERSION}) Initialized on {device}!')\n"
      ]
    },
    {
      "cell_type": "code",
      "id": "v5-config-2",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "def find_input_file(filename: str) -> str:\n",
        "    candidates = [\n",
        "        os.path.join('/kaggle/input/rsna-knee-abnormality-detection', filename),\n",
        "        os.path.join('/kaggle/input/rsna-knee-2026-gemini-weak-labels', filename),\n",
        "        os.path.join('contests/rsna_knee_2026', filename),\n",
        "        filename\n",
        "    ]\n",
        "    if os.path.exists('/kaggle/input'):\n",
        "        for root, dirs, files in os.walk('/kaggle/input'):\n",
        "            if filename in files:\n",
        "                return os.path.join(root, filename)\n",
        "    for c in candidates:\n",
        "        if os.path.exists(c):\n",
        "            return c\n",
        "    return filename\n",
        "\n",
        "def find_train_images_root() -> str:\n",
        "    if os.path.exists('/kaggle/input'):\n",
        "        for root, dirs, _ in os.walk('/kaggle/input'):\n",
        "            if 'train_images' in dirs:\n",
        "                cand = os.path.join(root, 'train_images')\n",
        "                if os.path.exists(cand):\n",
        "                    return cand\n",
        "    candidates = [\n",
        "        '/kaggle/input/competitions/rsna-knee-abnormality-detection/train_images',\n",
        "        '/kaggle/input/rsna-knee-abnormality-detection/train_images',\n",
        "        'train_images'\n",
        "    ]\n",
        "    for c in candidates:\n",
        "        if os.path.exists(c):\n",
        "            return c\n",
        "    return 'train_images'\n",
        "\n",
        "TRAIN_CSV = find_input_file('train.csv')\n",
        "SERIES_CSV = find_input_file('train_series.csv')\n",
        "TRAIN_IMAGES_DIR = find_train_images_root()\n",
        "\n",
        "# Hyperparameters\n",
        "BATCH_SIZE = 4\n",
        "NUM_EPOCHS = 5\n",
        "LR_MAX = 3e-4\n",
        "LR_MIN = 1e-6\n",
        "IMAGE_SIZE = 256\n",
        "NUM_SLICES_PER_PLANE = 16\n",
        "BACKBONE = 'resnet18'\n",
        "\n",
        "print(f'[OK] Configured inputs:')\n",
        "print(f'  Train CSV: {TRAIN_CSV}')\n",
        "print(f'  Series CSV: {SERIES_CSV}')\n",
        "print(f'  Images Dir: {TRAIN_IMAGES_DIR}')\n"
      ]
    },
    {
      "cell_type": "code",
      "id": "v5-dataset-3",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "class RSNAKneeDataset(Dataset):\n",
        "    def __init__(self, df: pd.DataFrame, series_df: pd.DataFrame, img_dir: str, is_train: bool = True):\n",
        "        self.df = df.reset_index(drop=True)\n",
        "        self.series_df = series_df\n",
        "        self.img_dir = img_dir\n",
        "        self.is_train = is_train\n",
        "        \n",
        "    def __len__(self):\n",
        "        return len(self.df)\n",
        "        \n",
        "    def apply_window(self, pixel_array: np.ndarray, center: float, width: float) -> np.ndarray:\n",
        "        min_val = center - width / 2.0\n",
        "        max_val = center + width / 2.0\n",
        "        windowed = np.clip(pixel_array, min_val, max_val)\n",
        "        return (windowed - min_val) / (max_val - min_val + 1e-6)\n",
        "        \n",
        "    def convert_to_3channel_rgb(self, slice_data: np.ndarray) -> np.ndarray:\n",
        "        ch0 = self.apply_window(slice_data, center=400, width=1000)\n",
        "        ch1 = self.apply_window(slice_data, center=700, width=2000)\n",
        "        grad_y, grad_x = np.gradient(ch0)\n",
        "        ch2 = np.sqrt(grad_x**2 + grad_y**2)\n",
        "        ch2 = np.clip(ch2 / (np.max(ch2) + 1e-6), 0, 1)\n",
        "        return np.stack([ch0, ch1, ch2], axis=0).astype(np.float32)\n",
        "        \n",
        "    def read_study_plane_slices(self, study_uid: str, plane: str) -> torch.Tensor:\n",
        "        matched = self.series_df[(self.series_df['StudyInstanceUID'] == study_uid) & \n",
        "                                 (self.series_df['Anatomical_Plane'] == plane)]\n",
        "        \n",
        "        tensor_out = torch.zeros((NUM_SLICES_PER_PLANE, 3, IMAGE_SIZE, IMAGE_SIZE), dtype=torch.float32)\n",
        "        if matched.empty:\n",
        "            return tensor_out\n",
        "            \n",
        "        series_uid = matched.iloc[0]['SeriesInstanceUID']\n",
        "        series_dir = os.path.join(self.img_dir, study_uid, series_uid)\n",
        "        if not os.path.exists(series_dir):\n",
        "            return tensor_out\n",
        "            \n",
        "        files = sorted([os.path.join(series_dir, f) for f in os.listdir(series_dir) if not f.startswith('.')])\n",
        "        if not files:\n",
        "            return tensor_out\n",
        "            \n",
        "        n_files = len(files)\n",
        "        if n_files > NUM_SLICES_PER_PLANE:\n",
        "            indices = np.linspace(0, n_files - 1, NUM_SLICES_PER_PLANE, dtype=int)\n",
        "            selected = [files[i] for i in indices]\n",
        "        else:\n",
        "            selected = files\n",
        "            \n",
        "        for idx, fp in enumerate(selected):\n",
        "            try:\n",
        "                ds = pydicom.dcmread(fp, force=True)\n",
        "                if not hasattr(ds, 'pixel_array'):\n",
        "                    ds.file_meta.TransferSyntaxUID = pydicom.uid.ImplicitVRLittleEndian\n",
        "                arr = ds.pixel_array.astype(np.float32)\n",
        "                t_arr = torch.tensor(arr).unsqueeze(0).unsqueeze(0)\n",
        "                t_resized = F.interpolate(t_arr, size=(IMAGE_SIZE, IMAGE_SIZE), mode='bilinear', align_corners=False)\n",
        "                resized = t_resized.squeeze().numpy()\n",
        "                tensor_out[idx] = torch.tensor(self.convert_to_3channel_rgb(resized))\n",
        "            except Exception:\n",
        "                pass\n",
        "        return tensor_out\n",
        "        \n",
        "    def __getitem__(self, idx: int) -> Dict[str, Any]:\n",
        "        row = self.df.iloc[idx]\n",
        "        study_uid = str(row['StudyInstanceUID'])\n",
        "        sag = self.read_study_plane_slices(study_uid, 'Sagittal')\n",
        "        cor = self.read_study_plane_slices(study_uid, 'Coronal')\n",
        "        ax = self.read_study_plane_slices(study_uid, 'Axial')\n",
        "        \n",
        "        labels = row[TARGET_COLS].values.astype(np.float32)\n",
        "        # Sample weight: 1.0 for gold standard, 0.40 for weak labels\n",
        "        sample_weight = 1.0 if row.get('label_source') == 'gold' else 0.40\n",
        "        \n",
        "        return {\n",
        "            'study_id': study_uid,\n",
        "            'sag': sag,\n",
        "            'cor': cor,\n",
        "            'ax': ax,\n",
        "            'labels': torch.tensor(labels),\n",
        "            'weight': torch.tensor(sample_weight, dtype=torch.float32)\n",
        "        }\n"
      ]
    },
    {
      "cell_type": "code",
      "id": "v5-loss-and-model-4",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "class AsymmetricLoss(nn.Module):\n",
        "    \"\"\"Asymmetric Loss (ASL) for multi-label classification with severe class imbalance.\"\"\"\n",
        "    def __init__(self, gamma_neg: float = 4.0, gamma_pos: float = 1.0, clip: float = 0.05, eps: float = 1e-8):\n",
        "        super().__init__()\n",
        "        self.gamma_neg = gamma_neg\n",
        "        self.gamma_pos = gamma_pos\n",
        "        self.clip = clip\n",
        "        self.eps = eps\n",
        "        \n",
        "    def forward(self, logits: torch.Tensor, targets: torch.Tensor, weights: Optional[torch.Tensor] = None) -> torch.Tensor:\n",
        "        probs = torch.sigmoid(logits)\n",
        "        probs_pos = probs\n",
        "        probs_neg = 1.0 - probs\n",
        "        \n",
        "        if self.clip > 0:\n",
        "            probs_neg = (probs_neg + self.clip).clamp(max=1.0)\n",
        "            \n",
        "        loss_pos = targets * torch.log(probs_pos.clamp(min=self.eps)) * ((1.0 - probs_pos) ** self.gamma_pos)\n",
        "        loss_neg = (1.0 - targets) * torch.log(probs_neg.clamp(min=self.eps)) * (probs_pos ** self.gamma_neg)\n",
        "        loss = -(loss_pos + loss_neg)\n",
        "        \n",
        "        if weights is not None:\n",
        "            loss = loss * weights.unsqueeze(-1)\n",
        "            \n",
        "        return loss.mean()\n",
        "\n",
        "class SliceAttentionPool(nn.Module):\n",
        "    def __init__(self, embed_dim: int = 512):\n",
        "        super().__init__()\n",
        "        self.attn = nn.Sequential(\n",
        "            nn.Linear(embed_dim, 128),\n            nn.Tanh(),\n",
        "            nn.Linear(128, 1)\n",
        "        )\n",
        "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n",
        "        weights = F.softmax(self.attn(x), dim=1)\n",
        "        return torch.sum(x * weights, dim=1)\n",
        "\n",
        "class MILKneeNet(nn.Module):\n",
        "    def __init__(self, num_targets: int = 12, backbone_name: str = 'resnet18'):\n",
        "        super().__init__()\n",
        "        self.num_targets = num_targets\n",
        "        base_model = torchvision.models.resnet18(weights=torchvision.models.ResNet18_Weights.DEFAULT if hasattr(torchvision.models, 'ResNet18_Weights') else None)\n",
        "        self.feature_dim = 512\n",
        "        self.backbone = nn.Sequential(*list(base_model.children())[:-1])\n",
        "        \n",
        "        self.sag_pool = SliceAttentionPool(self.feature_dim)\n",
        "        self.cor_pool = SliceAttentionPool(self.feature_dim)\n",
        "        self.ax_pool = SliceAttentionPool(self.feature_dim)\n",
        "        \n",
        "        self.classifier = nn.Sequential(\n",
        "            nn.Linear(self.feature_dim * 3, 256),\n",
        "            nn.GELU(),\n",
        "            nn.Dropout(0.3),\n",
        "            nn.Linear(256, num_targets)\n",
        "        )\n",
        "        \n",
        "    def extract_features(self, x: torch.Tensor) -> torch.Tensor:\n",
        "        B, S, C, H, W = x.shape\n",
        "        feats = self.backbone(x.view(B * S, C, H, W))\n",
        "        return feats.view(B, S, -1)\n",
        "        \n",
        "    def forward(self, sag: torch.Tensor, cor: torch.Tensor, ax: torch.Tensor) -> torch.Tensor:\n",
        "        sag_p = self.sag_pool(self.extract_features(sag))\n",
        "        cor_p = self.cor_pool(self.extract_features(cor))\n",
        "        ax_p = self.ax_pool(self.extract_features(ax))\n",
        "        return self.classifier(torch.cat([sag_p, cor_p, ax_p], dim=-1))\n",
        "\n",
        "print('[OK] AsymmetricLoss and MILKneeNet architecture defined.')\n"
      ]
    },
    {
      "cell_type": "code",
      "id": "v5-training-loop-5",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "df_all = pd.read_csv(TRAIN_CSV)\n",
        "series_df = pd.read_csv(SERIES_CSV)\n",
        "\n",
        "# Build 5-fold CV\n",
        "df_all['fold'] = -1\n",
        "unique_studies = df_all['StudyInstanceUID'].unique()\n",
        "kf = KFold(n_splits=5, shuffle=True, random_state=42)\n",
        "for fold, (_, val_idx) in enumerate(kf.split(unique_studies)):\n",
        "    df_all.loc[df_all['StudyInstanceUID'].isin(set(unique_studies[val_idx])), 'fold'] = fold\n",
        "\n",
        "device = get_safe_device()\n",
        "criterion = AsymmetricLoss(gamma_neg=4.0, gamma_pos=1.0, clip=0.05)\n",
        "\n",
        "print(f'[OK] Starting 5-Fold Training on {len(df_all)} studies with Continuous ASL...')\n",
        "\n",
        "for fold in range(5):\n",
        "    print(f'\\n=================== FOLD {fold} ===================')\n",
        "    train_subset = df_all[df_all['fold'] != fold]\n",
        "    val_subset = df_all[df_all['fold'] == fold]\n",
        "    \n",
        "    train_ds = RSNAKneeDataset(train_subset, series_df, TRAIN_IMAGES_DIR, is_train=True)\n",
        "    val_ds = RSNAKneeDataset(val_subset, series_df, TRAIN_IMAGES_DIR, is_train=False)\n",
        "    \n",
        "    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)\n",
        "    val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)\n",
        "    \n",
        "    model = MILKneeNet(backbone_name=BACKBONE).to(device)\n",
        "    optimizer = torch.optim.AdamW(model.parameters(), lr=LR_MAX, weight_decay=1e-2)\n",
        "    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=NUM_EPOCHS, eta_min=LR_MIN)\n",
        "    \n",
        "    for epoch in range(1, NUM_EPOCHS + 1):\n",
        "        model.train()\n",
        "        total_loss = 0.0\n",
        "        for batch in train_loader:\n",
        "            sag, cor, ax = batch['sag'].to(device), batch['cor'].to(device), batch['ax'].to(device)\n",
        "            labels, weights = batch['labels'].to(device), batch['weight'].to(device)\n",
        "            \n",
        "            optimizer.zero_grad()\n",
        "            logits = model(sag, cor, ax)\n",
        "            loss = criterion(logits, labels, weights)\n",
        "            loss.backward()\n",
        "            optimizer.step()\n",
        "            total_loss += loss.item() * sag.size(0)\n",
        "            \n",
        "        scheduler.step()\n",
        "        avg_loss = total_loss / len(train_ds)\n",
        "        print(f'  Epoch {epoch}/{NUM_EPOCHS} - ASL Loss: {avg_loss:.4f} - LR: {scheduler.get_last_lr()[0]:.6f}')\n",
        "        \n",
        "    # Save fold checkpoint\n",
        "    save_path = f'model_fold_{fold}.pth'\n",
        "    torch.save(model.state_dict(), save_path)\n",
        "    print(f'  [OK] Saved {save_path}')\n",
        "    gc.collect()\n",
        "    torch.cuda.empty_cache()\n",
        "\n",
        "print('\\n[OK] All 5 Folds trained and saved with Continuous Asymmetric Loss!')\n"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3 (ipykernel)",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.12.0"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}

out_path = r'c:\Users\philg\Pocketgull\pocketgull\contests\rsna_knee_2026\training_v5\rsna_knee_train_v5.ipynb'
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2)

print(f"Created {out_path} with {len(notebook['cells'])} cells.")
