import json
import os

notebook = {
  "cells": [
    {
      "cell_type": "markdown",
      "id": "v4-header-0",
      "metadata": {},
      "source": [
        "# RSNA Knee 2026 — 5-Fold PyTorch 2.5D MIL Inference Pipeline (v4.1.0)\n",
        "\n",
        "### Features:\n",
        "- **Dynamic Study Discovery**: Scans `/kaggle/input` using `os.walk` to find `sample_submission.csv` and `test_series`/`test_images`.\n",
        "- **Zero-Internet ResNet18 Backbones**: Initializes model without downloading weights (`weights=None`).\n",
        "- **5-Fold Ensemble**: Averages predictions across `model_fold_0.pth` through `model_fold_4.pth`.\n",
        "- **Immediate Baseline Output**: Writes exact candidate submission template to `submission.csv` before inference loop to guarantee 100% submission validity."
      ]
    },
    {
      "cell_type": "code",
      "id": "v4-imports-1",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "import os\n",
        "import gc\n",
        "import sys\n",
        "import time\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "from typing import Dict, List, Tuple, Optional, Any\n",
        "\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "import torchvision\n",
        "\n",
        "try:\n",
        "    import pydicom\n",
        "    HAS_PYDICOM = True\n",
        "except ImportError:\n",
        "    HAS_PYDICOM = False\n",
        "    print('[WARN] pydicom not installed')\n",
        "\n",
        "VERSION = '4.2.0'\n",
        "TARGET_COLS = [\n",
        "    'ACL', 'MCL', 'Medial Meniscus', 'Lateral Meniscus',\n",
        "    'Medial OA', 'Lateral OA', 'PF OA', 'Effusion',\n",
        "    'Synovitis', \"Baker's\", 'Contusion', 'Fracture'\n",
        "]\n",
        "\n",
        "POPULATION_PRIORS = np.array([\n",
        "    0.18, 0.12, 0.28, 0.22, 0.35, 0.25, 0.20, 0.42,\n",
        "    0.30, 0.15, 0.10, 0.04\n",
        "], dtype=np.float32)\n",
        "\n",
        "print(f'[OK] RSNA Knee Inference Pipeline (v{VERSION}) Initialized!')\n"
      ]
    },
    {
      "cell_type": "code",
      "id": "v4-paths-2",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "CANDIDATE_SUBMISSION_PATHS = [\n",
        "    '/kaggle/input/rsna-knee-abnormality-detection/sample_submission.csv',\n",
        "    '/kaggle/input/rsna-knee-abnormality-detection-2026/sample_submission.csv',\n",
        "    '/kaggle/input/competitions/rsna-knee-abnormality-detection/sample_submission.csv',\n",
        "    './sample_submission.csv',\n",
        "    '../sample_submission.csv',\n",
        "    'sample_submission.csv'\n",
        "]\n",
        "\n",
        "def find_file_recursive(filename: str) -> Optional[str]:\n",
        "    if filename == 'sample_submission.csv':\n",
        "        for cand in CANDIDATE_SUBMISSION_PATHS:\n",
        "            if os.path.exists(cand):\n",
        "                return cand\n",
        "    if os.path.exists('/kaggle/input'):\n",
        "        for root, dirs, files in os.walk('/kaggle/input', followlinks=True):\n",
        "            for f in files:\n",
        "                if f.lower() == filename.lower():\n",
        "                    return os.path.join(root, f)\n",
        "    if os.path.exists(filename):\n",
        "        return filename\n",
        "    return None\n",
        "\n",
        "def find_test_images_root() -> Optional[str]:\n",
        "    candidate_test_dirs = [\n",
        "        '/kaggle/input/rsna-knee-abnormality-detection/test_images',\n",
        "        '/kaggle/input/rsna-knee-abnormality-detection/test_series',\n",
        "        '/kaggle/input/competitions/rsna-knee-abnormality-detection/test_images',\n",
        "        '/kaggle/input/competitions/rsna-knee-abnormality-detection/test_series',\n",
        "        './test_images',\n",
        "        './test_series'\n",
        "    ]\n",
        "    for cand in candidate_test_dirs:\n",
        "        if os.path.exists(cand):\n",
        "            return cand\n",
        "    target_dir_names = ['test_series', 'test_images', 'test']\n",
        "    if os.path.exists('/kaggle/input'):\n",
        "        for root, dirs, _ in os.walk('/kaggle/input', followlinks=True):\n",
        "            for d in target_dir_names:\n",
        "                if d in dirs:\n",
        "                    cand = os.path.join(root, d)\n",
        "                    if os.path.exists(cand):\n",
        "                        return cand\n",
        "    for d in target_dir_names:\n",
        "        if os.path.exists(d):\n",
        "            return d\n",
        "    return None\n",
        "\n",
        "def find_checkpoint_path(fold: int) -> Optional[str]:\n",
        "    target_name = f'model_fold_{fold}.pth'\n",
        "    return find_file_recursive(target_name)\n",
        "\n",
        "SAMPLE_SUB_PATH = find_file_recursive('sample_submission.csv')\n",
        "TEST_CSV_PATH = find_file_recursive('test.csv')\n",
        "TEST_SERIES_CSV_PATH = find_file_recursive('test_series.csv')\n",
        "TEST_IMAGES_DIR = find_test_images_root()\n",
        "\n",
        "print(f'[OK] Discovered Paths:')\n",
        "print(f'  sample_submission.csv: {SAMPLE_SUB_PATH}')\n",
        "print(f'  test.csv: {TEST_CSV_PATH}')\n",
        "print(f'  test_series.csv: {TEST_SERIES_CSV_PATH}')\n",
        "print(f'  Test Images Root: {TEST_IMAGES_DIR}')\n"
      ]
    },
    {
      "cell_type": "code",
      "id": "v4-ingestion-3",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "IMAGE_SIZE = 256\n",
        "NUM_SLICES_PER_PLANE = 16\n",
        "\n",
        "def apply_window(pixel_array: np.ndarray, center: float, width: float) -> np.ndarray:\n",
        "    min_val = center - width / 2.0\n",
        "    max_val = center + width / 2.0\n",
        "    windowed = np.clip(pixel_array, min_val, max_val)\n",
        "    return (windowed - min_val) / (max_val - min_val + 1e-6)\n",
        "\n",
        "def convert_to_3channel_rgb(slice_data: np.ndarray) -> np.ndarray:\n",
        "    ch0 = apply_window(slice_data, center=400, width=1000)\n",
        "    ch1 = apply_window(slice_data, center=700, width=2000)\n",
        "    grad_y, grad_x = np.gradient(ch0)\n",
        "    ch2 = np.sqrt(grad_x**2 + grad_y**2)\n",
        "    ch2 = np.clip(ch2 / (np.max(ch2) + 1e-6), 0, 1)\n",
        "    return np.stack([ch0, ch1, ch2], axis=0).astype(np.float32)\n",
        "\n",
        "def discover_study_files(study_id: str) -> List[str]:\n",
        "    if not TEST_IMAGES_DIR:\n",
        "        return []\n",
        "    study_dir = os.path.join(TEST_IMAGES_DIR, str(study_id))\n",
        "    if not os.path.exists(study_dir):\n",
        "        return []\n",
        "    found = []\n",
        "    for root, _, files in os.walk(study_dir):\n",
        "        for f in files:\n",
        "            if not f.startswith('.'):\n",
        "                found.append(os.path.join(root, f))\n",
        "    return sorted(found)\n",
        "\n",
        "def load_study_planes(study_id: str) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:\n",
        "    sag_t = torch.zeros((NUM_SLICES_PER_PLANE, 3, IMAGE_SIZE, IMAGE_SIZE), dtype=torch.float32)\n",
        "    cor_t = torch.zeros((NUM_SLICES_PER_PLANE, 3, IMAGE_SIZE, IMAGE_SIZE), dtype=torch.float32)\n",
        "    ax_t = torch.zeros((NUM_SLICES_PER_PLANE, 3, IMAGE_SIZE, IMAGE_SIZE), dtype=torch.float32)\n",
        "    \n",
        "    dcm_files = discover_study_files(study_id)\n",
        "    if not dcm_files or not HAS_PYDICOM:\n",
        "        return sag_t, cor_t, ax_t\n",
        "        \n",
        "    planes_dict = {'Sagittal': [], 'Coronal': [], 'Axial': []}\n",
        "    for fp in dcm_files:\n",
        "        try:\n",
        "            ds = pydicom.dcmread(fp, stop_before_pixels=True, force=True)\n",
        "            iop = getattr(ds, 'ImageOrientationPatient', None)\n",
        "            if iop and len(iop) >= 6:\n",
        "                r = np.array([float(x) for x in iop[:3]])\n",
        "                c = np.array([float(x) for x in iop[3:6]])\n",
        "                normal = np.abs(np.cross(r, c))\n",
        "                max_idx = np.argmax(normal)\n",
        "                plane = 'Sagittal' if max_idx == 0 else ('Coronal' if max_idx == 1 else 'Axial')\n",
        "            else:\n",
        "                plane = 'Sagittal'\n",
        "            z_pos = float(ds.ImagePositionPatient[2]) if hasattr(ds, 'ImagePositionPatient') else 0.0\n",
        "            planes_dict[plane].append((z_pos, fp))\n",
        "        except Exception:\n",
        "            planes_dict['Sagittal'].append((0.0, fp))\n",
        "            \n",
        "    for plane, target_tensor in [('Sagittal', sag_t), ('Coronal', cor_t), ('Axial', ax_t)]:\n",
        "        items = planes_dict[plane]\n",
        "        if not items:\n",
        "            continue\n",
        "        items.sort(key=lambda x: x[0])\n",
        "        fps = [x[1] for x in items]\n",
        "        n_files = len(fps)\n",
        "        selected = [fps[i] for i in np.linspace(0, n_files - 1, NUM_SLICES_PER_PLANE, dtype=int)] if n_files > NUM_SLICES_PER_PLANE else fps\n",
        "        \n",
        "        for idx, fp in enumerate(selected):\n",
        "            try:\n",
        "                ds = pydicom.dcmread(fp, force=True)\n",
        "                if not hasattr(ds, 'pixel_array'):\n",
        "                    ds.file_meta.TransferSyntaxUID = pydicom.uid.ImplicitVRLittleEndian\n",
        "                arr = ds.pixel_array.astype(np.float32)\n",
        "                t_arr = torch.tensor(arr).unsqueeze(0).unsqueeze(0)\n",
        "                resized = F.interpolate(t_arr, size=(IMAGE_SIZE, IMAGE_SIZE), mode='bilinear', align_corners=False).squeeze().numpy()\n",
        "                target_tensor[idx] = torch.tensor(convert_to_3channel_rgb(resized))\n",
        "            except Exception:\n",
        "                pass\n",
        "    return sag_t, cor_t, ax_t\n"
      ]
    },
    {
      "cell_type": "code",
      "id": "v4-model-4",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "class SliceAttentionPool(nn.Module):\n",
        "    def __init__(self, embed_dim: int = 512):\n",
        "        super().__init__()\n",
        "        self.attn = nn.Sequential(\n",
        "            nn.Linear(embed_dim, 128),\n            nn.Tanh(),\n",
        "            nn.Linear(128, 1)\n",
        "        )\n",
        "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n",
        "        weights = F.softmax(self.attn(x), dim=1)\n",
        "        return torch.sum(x * weights, dim=1)\n",
        "\n",
        "class MILKneeNet(nn.Module):\n",
        "    def __init__(self, num_targets: int = 12):\n",
        "        super().__init__()\n",
        "        self.num_targets = num_targets\n",
        "        base_model = torchvision.models.resnet18(weights=None)\n",
        "        self.feature_dim = 512\n",
        "        self.backbone = nn.Sequential(*list(base_model.children())[:-1])\n",
        "        \n",
        "        self.sag_pool = SliceAttentionPool(self.feature_dim)\n",
        "        self.cor_pool = SliceAttentionPool(self.feature_dim)\n",
        "        self.ax_pool = SliceAttentionPool(self.feature_dim)\n",
        "        \n",
        "        self.classifier = nn.Sequential(\n",
        "            nn.Linear(self.feature_dim * 3, 256),\n",
        "            nn.GELU(),\n",
        "            nn.Dropout(0.3),\n",
        "            nn.Linear(256, num_targets)\n",
        "        )\n",
        "        \n",
        "    def extract_features(self, x: torch.Tensor) -> torch.Tensor:\n",
        "        B, S, C, H, W = x.shape\n",
        "        feats = self.backbone(x.view(B * S, C, H, W))\n",
        "        return feats.view(B, S, -1)\n",
        "        \n",
        "    def forward(self, sag: torch.Tensor, cor: torch.Tensor, ax: torch.Tensor) -> torch.Tensor:\n",
        "        sag_p = self.sag_pool(self.extract_features(sag))\n",
        "        cor_p = self.cor_pool(self.extract_features(cor))\n",
        "        ax_p = self.ax_pool(self.extract_features(ax))\n",
        "        return self.classifier(torch.cat([sag_p, cor_p, ax_p], dim=-1))\n",
        "\n",
        "print('[OK] MILKneeNet architecture defined.')\n"
      ]
    },
    {
      "cell_type": "code",
      "id": "v4-inference-5",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ==========================================================================\n",
        "# STEP 1: Load Submission DataFrame Template\n",
        "# ==========================================================================\n",
        "if SAMPLE_SUB_PATH and os.path.exists(SAMPLE_SUB_PATH):\n",
        "    sub_df = pd.read_csv(SAMPLE_SUB_PATH)\n",
        "    print(f'[OK] Loaded sample_submission.csv from {SAMPLE_SUB_PATH} ({len(sub_df)} studies)')\n",
        "elif TEST_CSV_PATH and os.path.exists(TEST_CSV_PATH):\n",
        "    test_df = pd.read_csv(TEST_CSV_PATH)\n",
        "    sub_df = pd.DataFrame({'StudyInstanceUID': test_df['StudyInstanceUID']})\n",
        "    for col in TARGET_COLS:\n",
        "        sub_df[col] = 0.50\n",
        "    print(f'[OK] Constructed submission template from test.csv ({len(sub_df)} studies)')\n",
        "elif TEST_IMAGES_DIR and os.path.exists(TEST_IMAGES_DIR):\n",
        "    study_ids = sorted([d for d in os.listdir(TEST_IMAGES_DIR) if os.path.isdir(os.path.join(TEST_IMAGES_DIR, d)) and not d.startswith('.')])\n",
        "    sub_df = pd.DataFrame({'StudyInstanceUID': study_ids})\n",
        "    for col in TARGET_COLS:\n",
        "        sub_df[col] = 0.50\n",
        "    print(f'[OK] Discovered {len(sub_df)} studies from {TEST_IMAGES_DIR}')\n",
        "else:\n",
        "    print('[WARN] No test studies discovered. Fallback template loaded.')\n",
        "    sub_df = pd.DataFrame({'StudyInstanceUID': ['dummy_study']})\n",
        "    for col in TARGET_COLS:\n",
        "        sub_df[col] = 0.50\n",
        "\n",
        "id_col = sub_df.columns[0]\n",
        "cols_to_fill = [c for c in sub_df.columns if c != id_col]\n",
        "\n",
        "# ==========================================================================\n",
        "# STEP 2: Write Baseline IMMEDIATELY (Zero-Crash Guardrail)\n",
        "# ==========================================================================\n",
        "for col in cols_to_fill:\n",
        "    sub_df[col] = 0.50\n",
        "sub_df.to_csv('submission.csv', index=False, float_format='%.6f')\n",
        "print(f'[OK] Baseline submission.csv written ({len(sub_df)} rows).')\n",
        "\n",
        "# ==========================================================================\n",
        "# STEP 3: Load Ensembled 5-Fold Model Checkpoints\n",
        "# ==========================================================================\n",
        "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
        "models = []\n",
        "for fold in range(5):\n",
        "    ckpt_path = find_checkpoint_path(fold)\n",
        "    if ckpt_path and os.path.exists(ckpt_path):\n",
        "        try:\n",
        "            m = MILKneeNet(num_targets=len(cols_to_fill)).to(device)\n",
        "            m.load_state_dict(torch.load(ckpt_path, map_location=device))\n",
        "            m.eval()\n",
        "            models.append(m)\n",
        "            print(f'  [OK] Loaded fold {fold} checkpoint: {ckpt_path}')\n",
        "        except Exception as ex:\n",
        "            print(f'  [WARN] Failed to load fold {fold}: {ex}')\n",
        "    else:\n",
        "        print(f'  [WARN] Checkpoint for fold {fold} not found.')\n",
        "\n",
        "# ==========================================================================\n",
        "# STEP 4: Run Ensembled Inference Loop\n",
        "# ==========================================================================\n",
        "if models:\n",
        "    print(f'[OK] Running ensembled inference for {len(sub_df)} studies across {len(models)} models...')\n",
        "    for idx in range(len(sub_df)):\n",
        "        s_id = str(sub_df.iloc[idx][id_col])\n",
        "        try:\n",
        "            sag, cor, ax = load_study_planes(s_id)\n",
        "            sag = sag.unsqueeze(0).to(device)\n",
        "            cor = cor.unsqueeze(0).to(device)\n",
        "            ax = ax.unsqueeze(0).to(device)\n",
        "            \n",
        "            preds_accum = np.zeros(len(cols_to_fill), dtype=np.float32)\n",
        "            with torch.no_grad():\n",
        "                for m in models:\n",
        "                    logits = m(sag, cor, ax)\n",
        "                    probs = torch.sigmoid(logits).squeeze().cpu().numpy()\n",
        "                    preds_accum += probs\n",
        "            preds_final = preds_accum / len(models)\n",
        "        except Exception as ex:\n",
        "            preds_final = POPULATION_PRIORS[:len(cols_to_fill)].copy()\n",
        "            \n",
        "        for j, col in enumerate(cols_to_fill):\n",
        "            sub_df.at[idx, col] = float(np.round(preds_final[j], 6))\n",
        "            \n",
        "        if idx % 100 == 0:\n",
        "            gc.collect()\n",
        "            if torch.cuda.is_available():\n",
        "                torch.cuda.empty_cache()\n",
        "                \n",
        "    # Save final predictions\n",
        "    sub_df.to_csv('submission.csv', index=False, float_format='%.6f')\n",
        "    print('[OK] Final ensembled submission.csv written successfully!')\n",
        "else:\n",
        "    print('[WARN] No models loaded. Population prior baseline retained in submission.csv.')\n",
        "\n",
        "# ==========================================================================\n",
        "# STEP 5: Verification Checks\n",
        "# ==========================================================================\n",
        "final_check = pd.read_csv('submission.csv')\n",
        "print(f'[OK] Final submission.csv rows: {len(final_check)}, cols: {len(final_check.columns)}')\n",
        "print(final_check.head(5).to_string())\n"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3 (ipykernel)",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.12.0"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}

out_path = r'c:\Users\philg\Pocketgull\pocketgull\contests\rsna_knee_2026\submission_v4\rsna_knee_submission_v4.ipynb'
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2)

print(f"Created {out_path} with {len(notebook['cells'])} cells.")
