import json
import os

def update_training_notebook():
    # Use absolute path to ensure it always writes to the workspace folder
    script_dir = os.path.dirname(os.path.abspath(__file__))
    nb_path = os.path.join(script_dir, '..', 'contests', 'rsna_knee_2026', 'rsna_knee_train.ipynb')
    nb_path = os.path.abspath(nb_path)
    
    # Cell 0: Header Documentation
    cell0_header = {
        "cell_type": "markdown",
        "id": "train-header-0",
        "metadata": {},
        "source": [
            "# RSNA Knee 2026 — PyTorch 2.5D MIL Training Pipeline (v1.0.0)\n",
            "\n",
            "This notebook trains a deep 2.5D vision model with Multiple Instance Learning (MIL) attention pooling on the competition DICOM studies using **Gemini-derived weak labels** and **expert gold labels**.\n",
            "\n",
            "### Pipeline Architecture:\n",
            "1. **Weak-Label Pretraining (Stage 1)**: Pretrains on all 4,407 studies using LLM weak labels weighted by confidence.\n",
            "2. **Gold-Label Fine-Tuning (Stage 2)**: Fine-tunes only on the 58 gold-standard studies.\n",
            "3. **2.5D RGB Triplet Stacking**: Channel 0 (Red) = Soft Tissue, Channel 1 (Green) = Edema/Fluid, Channel 2 (Blue) = Sobel High-Pass Gradient.\n",
            "4. **5-Fold GroupKFold Cross-Validation**: Prevents study/patient leakage during validation.\n",
            "5. **MIL Attention Pooling**: Learns dynamically which slices contain the abnormalities rather than uniform averaging."
        ]
    }

    # Cell 1: Environment & Primary Imports
    cell1_imports = {
        "cell_type": "code",
        "id": "train-imports-1",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import gc\n",
            "import sys\n",
            "import time\n",
            "import math\n",
            "import random\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "from typing import Dict, List, Tuple, Optional, Any\n",
            "from sklearn.metrics import roc_auc_score\n",
            "from sklearn.model_selection import KFold\n",
            "\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "import torch.nn.functional as F\n",
            "from torch.utils.data import Dataset, DataLoader\n",
            "import torchvision\n",
            "from torchvision import transforms\n",
            "\n",
            "try:\n",
            "    import pydicom\n",
            "    HAS_PYDICOM = True\n",
            "except ImportError:\n",
            "    HAS_PYDICOM = False\n",
            "    print('[WARN] pydicom not installed. Please run: pip install pydicom')\n",
            "\n",
            "try:\n",
            "    from scipy import ndimage\n",
            "    HAS_SCIPY = True\n",
            "except ImportError:\n",
            "    HAS_SCIPY = False\n",
            "\n",
            "VERSION = '4.0.0'\n",
            "TARGET_COLS = [\n",
            "    'ACL', 'MCL', 'Medial Meniscus', 'Lateral Meniscus',\n",
            "    'Medial OA', 'Lateral OA', 'PF OA', 'Effusion',\n",
            "    'Synovitis', \"Baker's\", 'Contusion', 'Fracture'\n",
            "]\n",
            "\n",
            "def seed_everything(seed=42):\n",
            "    random.seed(seed)\n",
            "    os.environ['PYTHONHASHSEED'] = str(seed)\n",
            "    np.random.seed(seed)\n",
            "    torch.manual_seed(seed)\n",
            "    torch.cuda.manual_seed(seed)\n",
            "    torch.backends.cudnn.deterministic = True\n",
            "\n",
            "seed_everything()\n",
            "print(f'[OK] PyTorch training environment initialized! Version: {VERSION}')\n",
            "print(f'Using Device: {\"cuda\" if torch.cuda.is_available() else \"cpu\"}')\n"
        ]
    }

    # Cell 2: Hyperparameters & Path Configuration
    cell2_hyperparams = {
        "cell_type": "code",
        "id": "train-config-2",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Paths\n",
            "def find_input_file(filename: str, default_dir: str) -> str:\n",
            "    # List of candidate paths on Kaggle and local\n",
            "    candidates = [\n",
            "        os.path.join('/kaggle/input/rsna-knee-abnormality-detection', filename),\n",
            "        os.path.join('/kaggle/input/rsna-knee-2026-gemini-weak-labels', filename),\n",
            "        os.path.join('contests/rsna_knee_2026', filename),\n",
            "        filename\n",
            "    ]\n",
            "    # Also scan any subdirectories in /kaggle/input/\n",
            "    if os.path.exists('/kaggle/input'):\n",
            "        for root, dirs, files in os.walk('/kaggle/input'):\n",
            "            if filename in files:\n",
            "                return os.path.join(root, filename)\n",
            "    for c in candidates:\n",
            "        if os.path.exists(c):\n",
            "            return c\n",
            "    return os.path.join(default_dir, filename)\n",
            "\n",
            "def find_images_dir(series_csv_path: Optional[str] = None) -> str:\n",
            "    # 1. Check relative to resolved series_csv\n",
            "    if series_csv_path and os.path.exists(series_csv_path):\n",
            "        parent = os.path.dirname(series_csv_path)\n",
            "        cand = os.path.join(parent, 'train_images')\n",
            "        if os.path.exists(cand):\n",
            "            return cand\n",
            "    # 2. Dynamic walk across /kaggle/input for train_images folder\n",
            "    if os.path.exists('/kaggle/input'):\n",
            "        for root, dirs, _ in os.walk('/kaggle/input'):\n",
            "            if 'train_images' in dirs:\n",
            "                cand = os.path.join(root, 'train_images')\n",
            "                if os.path.exists(cand):\n",
            "                    return cand\n",
            "    # 3. Known candidates fallback\n",
            "    candidates = [\n",
            "        '/kaggle/input/competitions/rsna-knee-abnormality-detection/train_images',\n",
            "        '/kaggle/input/rsna-knee-abnormality-detection/train_images',\n",
            "        'contests/rsna_knee_2026/train_images',\n",
            "        'train_images'\n",
            "    ]\n",
            "    for c in candidates:\n",
            "        if os.path.exists(c):\n",
            "            return c\n",
            "    return candidates[0]\n",
            "\n",
            "TRAIN_CSV = find_input_file('train_labels_gemini.csv', 'contests/rsna_knee_2026')\n",
            "SERIES_CSV = find_input_file('train_series.csv', 'contests/rsna_knee_2026')\n",
            "TRAIN_IMAGES_DIR = find_images_dir(SERIES_CSV)\n",
            "\n",
            "print(f'[OK] Resolved paths:\\n  CSV: {TRAIN_CSV}\\n  Series: {SERIES_CSV}\\n  Images: {TRAIN_IMAGES_DIR}')\n",
            "if os.path.exists(TRAIN_IMAGES_DIR):\n",
            "    num_studies = len([d for d in os.listdir(TRAIN_IMAGES_DIR) if not d.startswith('.')])\n",
            "    print(f'[OK] Verified Images Directory: {num_studies} study folders present.')\n",
            "else:\n",
            "    print(f'[WARN] Images directory not found at {TRAIN_IMAGES_DIR}. Listing /kaggle/input structure:')\n",
            "    if os.path.exists('/kaggle/input'):\n",
            "        for root, dirs, files in os.walk('/kaggle/input'):\n",
            "            print(f'  {root} -> dirs: {dirs[:5]}, files: {files[:5]}')\n",
            "\n",
            "# Device Selection & CUDA Capability Check\n",
            "if torch.cuda.is_available():\n",
            "    gpu_name = torch.cuda.get_device_name(0)\n",
            "    cap = torch.cuda.get_device_capability(0)\n",
            "    print(f'[OK] CUDA Accelerator: {gpu_name} (Compute Capability: {cap[0]}.{cap[1]})')\n",
            "    if cap[0] < 7:\n",
            "        print(f'[WARN] {gpu_name} is compute capability sm_{cap[0]}{cap[1]} < sm_70. Modern PyTorch 2.6+ requires sm_70+ (T4/V100/A100). Please select GPU T4 in Kaggle session options.')\n",
            "else:\n",
            "    print('[INFO] Running on CPU.')\n",
            "\n",
            "# Hyperparameters\n",
            "BATCH_SIZE = 4\n",
            "NUM_EPOCHS_WEAK = 3      # Stage 1: Pretraining on weak labels\n",
            "NUM_EPOCHS_GOLD = 5      # Stage 2: Fine-tuning on gold labels\n",
            "LR_WEAK = 1e-4\n",
            "LR_GOLD = 2e-5\n",
            "IMAGE_SIZE = 256\n",
            "NUM_SLICES_PER_PLANE = 16\n",
            "BACKBONE = 'resnet18'\n",
            "\n",
            "print(f'[OK] Configuration loaded. Train CSV: {TRAIN_CSV}')\n"
        ]
    }

    # Cell 3: GroupKFold & Split Logic
    cell3_splitter = {
        "cell_type": "code",
        "id": "train-split-3",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def build_cv_splits(train_path: str, n_splits: int = 5) -> pd.DataFrame:\n",
            "    \"\"\"Generates 5-fold splits grouped by StudyInstanceUID to prevent leakage.\"\"\"\n",
            "    df = pd.read_csv(train_path)\n",
            "    df['fold'] = -1\n",
            "    \n",
            "    # In this dataset, StudyInstanceUID is unique per study, so splitting by StudyInstanceUID\n",
            "    # guarantees zero leakage across studies.\n",
            "    unique_studies = df['StudyInstanceUID'].unique()\n",
            "    kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)\n",
            "    \n",
            "    for fold, (_, val_idx) in enumerate(kf.split(unique_studies)):\n",
            "        val_studies = set(unique_studies[val_idx])\n",
            "        df.loc[df['StudyInstanceUID'].isin(val_studies), 'fold'] = fold\n",
            "        \n",
            "    print(f'[OK] Generated {n_splits}-fold splits.')\n",
            "    for f in range(n_splits):\n",
            "        f_df = df[df['fold'] == f]\n",
            "        gold_cnt = (f_df['label_source'] == 'gold').sum()\n",
            "        gemini_cnt = (f_df['label_source'] == 'gemini').sum()\n",
            "        print(f'  Fold {f}: {len(f_df)} studies (Gold: {gold_cnt}, Gemini: {gemini_cnt})')\n",
            "    return df\n",
            "\n",
            "df_all = build_cv_splits(TRAIN_CSV)\n"
        ]
    }

    # Cell 4: 2.5D RGB Windowing & Dataset Class
    cell4_dataset = {
        "cell_type": "code",
        "id": "train-dataset-4",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "class RSNAKneeDataset(Dataset):\n",
            "    \"\"\"Reads multi-plane DICOM slice stacks and builds 2.5D windowed RGB representations.\"\"\"\n",
            "    def __init__(self, df: pd.DataFrame, series_df: pd.DataFrame, img_dir: str, mode: str = 'train'):\n",
            "        self.df = df.reset_index(drop=True)\n",
            "        self.series_df = series_df\n",
            "        self.img_dir = img_dir\n",
            "        self.mode = mode\n",
            "        \n",
            "    def __len__(self):\n",
            "        return len(self.df)\n",
            "        \n",
            "    def apply_window(self, pixel_array: np.ndarray, center: float, width: float) -> np.ndarray:\n",
            "        min_val = center - width / 2.0\n",
            "        max_val = center + width / 2.0\n",
            "        windowed = np.clip(pixel_array, min_val, max_val)\n",
            "        return (windowed - min_val) / (max_val - min_val + 1e-6)\n",
            "        \n",
            "    def convert_to_3channel_rgb(self, slice_data: np.ndarray) -> np.ndarray:\n",
            "        # Channel 0: Soft Tissue\n",
            "        ch0 = self.apply_window(slice_data, center=400, width=1000)\n",
            "        # Channel 1: Fluid-Sensitive Edema\n",
            "        ch1 = self.apply_window(slice_data, center=700, width=2000)\n",
            "        # Channel 2: Sobel Edge Gradient\n",
            "        grad_y, grad_x = np.gradient(ch0)\n",
            "        ch2 = np.sqrt(grad_x**2 + grad_y**2)\n",
            "        ch2 = np.clip(ch2 / (np.max(ch2) + 1e-6), 0, 1)\n",
            "        return np.stack([ch0, ch1, ch2], axis=0).astype(np.float32)  # (3, H, W)\n",
            "        \n",
            "    def read_study_plane_slices(self, study_uid: str, plane: str) -> torch.Tensor:\n",
            "        \"\"\"Reads up to 16 sorted slices for a specific study plane.\"\"\"\n",
            "        # Find series matching plane\n",
            "        matched = self.series_df[(self.series_df['StudyInstanceUID'] == study_uid) & \n",
            "                                 (self.series_df['Anatomical_Plane'] == plane)]\n",
            "        \n",
            "        tensor_out = torch.zeros((NUM_SLICES_PER_PLANE, 3, IMAGE_SIZE, IMAGE_SIZE), dtype=torch.float32)\n",
            "        if matched.empty:\n",
            "            return tensor_out\n",
            "            \n",
            "        series_uid = matched.iloc[0]['SeriesInstanceUID']\n",
            "        series_dir = os.path.join(self.img_dir, study_uid, series_uid)\n",
            "        \n",
            "        if not os.path.exists(series_dir):\n",
            "            return tensor_out\n",
            "            \n",
            "        # Discover files and sort by ImagePositionPatient[2] (z-coordinate)\n",
            "        slices_info = []\n",
            "        for root, _, files in os.walk(series_dir):\n",
            "            for f in files:\n",
            "                if f.startswith('.'):\n",
            "                    continue\n",
            "                filepath = os.path.join(root, f)\n",
            "                try:\n",
            "                    ds = pydicom.dcmread(filepath, stop_before_pixels=True, force=True)\n",
            "                    z_pos = float(ds.ImagePositionPatient[2]) if hasattr(ds, 'ImagePositionPatient') else 0.0\n",
            "                    slices_info.append((z_pos, filepath))\n",
            "                except Exception:\n",
            "                    slices_info.append((0.0, filepath))\n",
            "                    \n",
            "        if not slices_info:\n",
            "            return tensor_out\n",
            "            \n",
            "        # Sort by z-coordinate\n",
            "        slices_info.sort(key=lambda x: x[0])\n",
            "        filepaths = [x[1] for x in slices_info]\n",
            "        \n",
            "        # Subsample to NUM_SLICES_PER_PLANE\n",
            "        n_files = len(filepaths)\n",
            "        if n_files > NUM_SLICES_PER_PLANE:\n",
            "            indices = np.linspace(0, n_files - 1, NUM_SLICES_PER_PLANE, dtype=int)\n",
            "            selected_paths = [filepaths[i] for i in indices]\n",
            "        else:\n",
            "            selected_paths = filepaths\n",
            "            \n",
            "        for idx, fp in enumerate(selected_paths):\n",
            "            try:\n",
            "                ds = pydicom.dcmread(fp, force=True)\n",
            "                if not hasattr(ds, 'pixel_array'):\n",
            "                    ds.file_meta.TransferSyntaxUID = pydicom.uid.ImplicitVRLittleEndian\n",
            "                arr = ds.pixel_array.astype(np.float32)\n",
            "                \n",
            "                # Resize to target image size\n",
            "                t_arr = torch.tensor(arr).unsqueeze(0).unsqueeze(0)\n",
            "                t_resized = F.interpolate(t_arr, size=(IMAGE_SIZE, IMAGE_SIZE), mode='bilinear', align_corners=False)\n",
            "                resized_arr = t_resized.squeeze().numpy()\n",
            "                \n",
            "                rgb = self.convert_to_3channel_rgb(resized_arr)\n",
            "                tensor_out[idx] = torch.tensor(rgb)\n",
            "            except Exception:\n",
            "                pass\n",
            "                \n",
            "        return tensor_out\n",
            "        \n",
            "    def __getitem__(self, idx):\n",
            "        row = self.df.iloc[idx]\n",
            "        study_uid = str(row['StudyInstanceUID'])\n",
            "        \n",
            "        # Load 3 planes\n",
            "        sag = self.read_study_plane_slices(study_uid, 'Sagittal')\n",
            "        cor = self.read_study_plane_slices(study_uid, 'Coronal')\n",
            "        ax = self.read_study_plane_slices(study_uid, 'Axial')\n",
            "        \n",
            "        labels = row[TARGET_COLS].values.astype(np.float32)\n",
            "        \n",
            "        # Extracted labels confidence vectors\n",
            "        conf_cols = [f'{col}_confidence' for col in TARGET_COLS]\n",
            "        confidences = row[conf_cols].values.astype(np.float32)\n",
            "        \n",
            "        return {\n",
            "            'sag': sag,\n",
            "            'cor': cor,\n",
            "            'ax': ax,\n",
            "            'labels': torch.tensor(labels),\n",
            "            'confidences': torch.tensor(confidences),\n",
            "            'source_gold': 1.0 if row['label_source'] == 'gold' else 0.0\n",
            "        }\n",
            "\n",
            "series_df = pd.read_csv(SERIES_CSV)\n",
            "print('[OK] Dataset class and metadata loaded.')\n"
        ]
    }

    # Cell 5: PyTorch Model Definition
    cell5_model = {
        "cell_type": "code",
        "id": "train-model-5",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "class SliceAttentionPool(nn.Module):\n",
            "    def __init__(self, embed_dim: int = 512):\n",
            "        super().__init__()\n",
            "        self.attn = nn.Sequential(\n",
            "            nn.Linear(embed_dim, 128),\n            nn.Tanh(),\n",
            "            nn.Linear(128, 1)\n",
            "        )\n",
            "        \n",
            "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n",
            "        # x shape: (B, Slices, EmbedDim)\n",
            "        weights = self.attn(x)  # (B, Slices, 1)\n",
            "        weights = F.softmax(weights, dim=1)\n",
            "        pooled = torch.sum(x * weights, dim=1)\n",
            "        return pooled\n",
            "\n",
            "class MILKneeNet(nn.Module):\n",
            "    def __init__(self, num_targets: int = 12, backbone_name: str = 'resnet18'):\n",
            "        super().__init__()\n",
            "        self.num_targets = num_targets\n",
            "        \n",
            "        # Vision backbone (pretrained ResNet18/34)\n",
            "        if backbone_name == 'resnet18':\n",
            "            base_model = torchvision.models.resnet18(pretrained=True)\n",
            "            self.feature_dim = 512\n",
            "        else:\n",
            "            base_model = torchvision.models.resnet34(pretrained=True)\n",
            "            self.feature_dim = 512\n",
            "            \n",
            "        # Remove FC layers\n",
            "        self.backbone = nn.Sequential(*list(base_model.children())[:-1])\n",
            "        \n",
            "        # Slice attention poolers for each plane\n",
            "        self.sag_pool = SliceAttentionPool(self.feature_dim)\n",
            "        self.cor_pool = SliceAttentionPool(self.feature_dim)\n",
            "        self.ax_pool = SliceAttentionPool(self.feature_dim)\n",
            "        \n",
            "        # Vision aggregation head\n",
            "        self.classifier = nn.Sequential(\n",
            "            nn.Linear(self.feature_dim * 3, 256),\n",
            "            nn.GELU(),\n",
            "            nn.Dropout(0.3),\n",
            "            nn.Linear(256, num_targets)\n",
            "        )\n",
            "        \n",
            "    def extract_features(self, x: torch.Tensor) -> torch.Tensor:\n",
            "        # x shape: (B, Slices, 3, H, W)\n",
            "        B, S, C, H, W = x.shape\n",
            "        x_flat = x.view(B * S, C, H, W)\n",
            "        feats = self.backbone(x_flat)  # (B * S, EmbedDim, 1, 1)\n",
            "        feats = feats.view(B, S, -1)   # (B, S, EmbedDim)\n",
            "        return feats\n",
            "        \n",
            "    def forward(self, sag: torch.Tensor, cor: torch.Tensor, ax: torch.Tensor) -> torch.Tensor:\n",
            "        sag_feats = self.extract_features(sag)\n",
            "        cor_feats = self.extract_features(cor)\n",
            "        ax_feats = self.extract_features(ax)\n",
            "        \n",
            "        sag_pooled = self.sag_pool(sag_feats)\n",
            "        cor_pooled = self.cor_pool(cor_feats)\n",
            "        ax_pooled = self.ax_pool(ax_feats)\n",
            "        \n",
            "        merged = torch.cat([sag_pooled, cor_pooled, ax_pooled], dim=-1)\n",
            "        logits = self.classifier(merged)\n",
            "        return logits\n",
            "\n",
            "model_smoke = MILKneeNet(backbone_name=BACKBONE)\n",
            "print('[OK] MILKneeNet model loaded.')\n"
        ]
    }

    # Cell 6: Multi-Stage Loss & Training Loop Functions
    cell6_training = {
        "cell_type": "code",
        "id": "train-loop-6",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def calculate_macro_auc(y_true: np.ndarray, y_pred: np.ndarray) -> float:\n",
            "    aucs = []\n",
            "    for i in range(y_true.shape[1]):\n",
            "        if len(np.unique(y_true[:, i])) > 1:\n",
            "            aucs.append(roc_auc_score(y_true[:, i], y_pred[:, i]))\n",
            "        else:\n",
            "            aucs.append(0.5)\n",
            "    return float(np.mean(aucs))\n",
            "\n",
            "def train_epoch(model, loader, optimizer, criterion, device, stage='weak'):\n",
            "    model.train()\n",
            "    total_loss = 0.0\n",
            "    for batch in loader:\n",
            "        sag = batch['sag'].to(device)\n",
            "        cor = batch['cor'].to(device)\n",
            "        ax = batch['ax'].to(device)\n",
            "        labels = batch['labels'].to(device)\n",
            "        conf = batch['confidences'].to(device)\n",
            "        \n",
            "        optimizer.zero_grad()\n",
            "        logits = model(sag, cor, ax)\n",
            "        \n",
            "        # Weighted BCE Loss based on label confidence\n",
            "        loss_raw = F.binary_cross_entropy_with_logits(logits, labels, reduction='none')\n",
            "        if stage == 'weak':\n",
            "            # Weight the loss by extraction confidence\n",
            "            loss = torch.mean(loss_raw * conf)\n",
            "        else:\n",
            "            loss = torch.mean(loss_raw)\n",
            "            \n",
            "        loss.backward()\n",
            "        optimizer.step()\n",
            "        total_loss += loss.item() * sag.size(0)\n",
            "        \n",
            "    return total_loss / len(loader.dataset)\n",
            "\n",
            "def evaluate_oof(model, loader, device):\n",
            "    model.eval()\n",
            "    all_preds = []\n",
            "    all_targets = []\n",
            "    with torch.no_grad():\n",
            "        for batch in loader:\n",
            "            sag = batch['sag'].to(device)\n",
            "            cor = batch['cor'].to(device)\n",
            "            ax = batch['ax'].to(device)\n",
            "            labels = batch['labels']\n",
            "            \n",
            "            logits = model(sag, cor, ax)\n",
            "            preds = torch.sigmoid(logits).cpu().numpy()\n",
            "            all_preds.append(preds)\n",
            "            all_targets.append(labels.numpy())\n",
            "            \n",
            "    return np.concatenate(all_targets, axis=0), np.concatenate(all_preds, axis=0)\n"
        ]
    }

    # Cell 7: Full 5-Fold Training Runner
    cell7_runner = {
        "cell_type": "code",
        "id": "train-run-7",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
            "oof_predictions = np.zeros((len(df_all), 12))\n",
            "oof_targets = np.zeros((len(df_all), 12))\n",
            "\n",
            "for fold in range(5):\n",
            "    print(f'\\n=================== FOLD {fold} ===================')\n",
            "    \n",
            "    # Split train/val\n",
            "    train_df = df_all[df_all['fold'] != fold]\n",
            "    val_df = df_all[df_all['fold'] == fold]\n",
            "    \n",
            "    # Filter gold-standard ONLY for validation evaluation\n",
            "    val_gold_df = val_df[val_df['label_source'] == 'gold']\n",
            "    \n",
            "    # Datasets\n",
            "    train_ds = RSNAKneeDataset(train_df, series_df, TRAIN_IMAGES_DIR, mode='train')\n",
            "    # Validate only on gold-standard labels to get the true competition metric\n",
            "    val_ds = RSNAKneeDataset(val_gold_df, series_df, TRAIN_IMAGES_DIR, mode='val')\n",
            "    \n",
            "    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, drop_last=True)\n",
            "    val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)\n",
            "    \n",
            "    model = MILKneeNet(backbone_name=BACKBONE).to(device)\n",
            "    \n",
            "    # ────────────────────────────────────────────────────────\n",
            "    # STAGE 1: Pretrain on weak + gold labels (All training data)\n",
            "    # ────────────────────────────────────────────────────────\n",
            "    print('  [STAGE 1] Training on Weak + Gold Labels...')\n",
            "    optimizer = torch.optim.AdamW(model.parameters(), lr=LR_WEAK, weight_decay=1e-4)\n",
            "    for epoch in range(NUM_EPOCHS_WEAK):\n",
            "        loss = train_epoch(model, train_loader, optimizer, nn.BCEWithLogitsLoss(), device, stage='weak')\n",
            "        print(f'    Epoch {epoch+1}/{NUM_EPOCHS_WEAK} Loss: {loss:.4f}')\n",
            "        \n",
            "    # ────────────────────────────────────────────────────────\n",
            "    # STAGE 2: Fine-tune strictly on gold labels\n",
            "    # ────────────────────────────────────────────────────────\n",
            "    print('  [STAGE 2] Fine-tuning strictly on Gold Labels...')\n",
            "    # Filter train df for gold standard only\n",
            "    train_gold_df = train_df[train_df['label_source'] == 'gold']\n",
            "    if not train_gold_df.empty:\n",
            "        train_gold_ds = RSNAKneeDataset(train_gold_df, series_df, TRAIN_IMAGES_DIR, mode='train')\n",
            "        train_gold_loader = DataLoader(train_gold_ds, batch_size=min(len(train_gold_df), BATCH_SIZE), shuffle=True)\n",
            "        \n",
            "        optimizer = torch.optim.AdamW(model.parameters(), lr=LR_GOLD, weight_decay=1e-4)\n",
            "        for epoch in range(NUM_EPOCHS_GOLD):\n",
            "            loss = train_epoch(model, train_gold_loader, optimizer, nn.BCEWithLogitsLoss(), device, stage='gold')\n",
            "            print(f'    Fine-tune Epoch {epoch+1}/{NUM_EPOCHS_GOLD} Loss: {loss:.4f}')\n",
            "            \n",
            "    # Save fold checkpoint\n",
            "    torch.save(model.state_dict(), f'model_fold_{fold}.pth')\n",
            "    print(f'  [OK] Saved model_fold_{fold}.pth')\n",
            "    \n",
            "    # Evaluate Out-of-Fold\n",
            "    if len(val_ds) > 0:\n",
            "        targets, preds = evaluate_oof(model, val_loader, device)\n",
            "        val_auc = calculate_macro_auc(targets, preds)\n",
            "        print(f'  [OK] Fold {fold} Validation Macro-AUC: {val_auc:.4f}')\n",
            "        \n",
            "        # Fill OOF maps\n",
            "        val_indices = val_gold_df.index\n",
            "        oof_predictions[val_indices] = preds\n",
            "        oof_targets[val_indices] = targets\n",
            "        \n",
            "print('\\n[OK] Training completed!')\n",
            "gold_indices = df_all[df_all['label_source'] == 'gold'].index\n",
            "if len(gold_indices) > 0:\n",
            "    final_auc = calculate_macro_auc(oof_targets[gold_indices], oof_predictions[gold_indices])\n",
            "    print(f'OOF Final Gold-Standard Macro-AUC: {final_auc:.4f}')\n"
        ]
    }

    notebook = {
        "cells": [
            cell0_header, 
            cell1_imports, 
            cell2_hyperparams, 
            cell3_splitter, 
            cell4_dataset, 
            cell5_model, 
            cell6_training, 
            cell7_runner
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.12.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }

    with open(nb_path, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=2)

    print(f'[OK] Generated training notebook: {nb_path}')

if __name__ == '__main__':
    update_training_notebook()
