# scripts/wp_provision.ps1
# Automated WP-CLI Provisioner for Windows PowerShell

$ErrorActionPreference = "Continue"

Write-Host "⏳ Checking WordPress database connection..." -ForegroundColor Cyan
docker exec -i pocketgull_wp_cli wp db check --quiet

$wpAdminUser = if ($env:WP_ADMIN_USER) { $env:WP_ADMIN_USER } else { "clinical_admin" }
$wpAdminPass = if ($env:WP_ADMIN_PASS) { $env:WP_ADMIN_PASS } else { "AutoGeneratedDevSecret" }

Write-Host "🚀 Installing WordPress Core..." -ForegroundColor Green
docker exec -i pocketgull_wp_cli wp core install `
  --url="http://localhost:8080" `
  --title="Pocket-Gull Articles & Clinical Knowledge" `
  --admin_user="$wpAdminUser" `
  --admin_password="$wpAdminPass" `
  --admin_email="editorial@pocketgull.com" `
  --skip-email

Write-Host "🎨 Activating Pocket-Gull Theme..." -ForegroundColor Yellow
docker exec -i pocketgull_wp_cli wp theme activate pocketgull-articles

Write-Host "🧬 Registering SNO-10 Categories..." -ForegroundColor Magenta
docker exec -i pocketgull_wp_cli wp term create sno10_condition "Hypertension (I10 / SNOMED 38341003)" --slug="hypertension"
docker exec -i pocketgull_wp_cli wp term create sno10_condition "Heart Failure (I50.9 / SNOMED 84114007)" --slug="heart-failure"
docker exec -i pocketgull_wp_cli wp term create sno10_condition "Osteoarthritis & Joint Care (M17.9)" --slug="osteoarthritis"
docker exec -i pocketgull_wp_cli wp term create sno10_condition "Preventive Nephrology (N18.9)" --slug="kidney-health"
docker exec -i pocketgull_wp_cli wp term create sno10_condition "Bereavement & Craft Continuity" --slug="craft-bereavement"

Write-Host "👤 Creating Author..." -ForegroundColor Cyan
docker exec -i pocketgull_wp_cli wp user create phil phil@pocketgull.com --role=author --display_name="Phil"

Write-Host "📰 Setting Permalinks structure to /%postname%/..." -ForegroundColor White
docker exec -i pocketgull_wp_cli wp rewrite structure '/%postname%/' --hard

Write-Host "✨ WordPress Provisioning Complete! Site is live at http://localhost:8080" -ForegroundColor Green
