#!/usr/bin/env bash
# scripts/wp_provision.sh
# Automated WP-CLI Provisioner for Pocket-Gull Articles Hub

set -e

WP_CLI="docker exec -i pocketgull_wp_cli wp"
SITE_URL="http://localhost:8080"
ADMIN_USER="${WP_ADMIN_USER:-clinical_admin}"
ADMIN_PASS="${WP_ADMIN_PASS:-AutoGeneratedDevSecret}"
ADMIN_EMAIL="editorial@pocketgull.com"

echo "⏳ Checking WordPress database connection..."
until $WP_CLI db check --quiet; do
  echo "Waiting for MariaDB to initialize..."
  sleep 3
done

echo "🚀 Installing WordPress Core..."
$WP_CLI core install \
  --url="$SITE_URL" \
  --title="Pocket-Gull Articles & Clinical Knowledge" \
  --admin_user="$ADMIN_USER" \
  --admin_password="$ADMIN_PASS" \
  --admin_email="$ADMIN_EMAIL" \
  --skip-email || echo "Core already installed."

echo "🎨 Activating Pocket-Gull Theme..."
$WP_CLI theme activate pocketgull-articles

echo "🧬 Registering SNO-10 Categories..."
$WP_CLI term create sno10_condition "Hypertension (I10 / SNOMED 38341003)" --slug="hypertension" || true
$WP_CLI term create sno10_condition "Heart Failure (I50.9 / SNOMED 84114007)" --slug="heart-failure" || true
$WP_CLI term create sno10_condition "Osteoarthritis & Joint Care (M17.9)" --slug="osteoarthritis" || true
$WP_CLI term create sno10_condition "Preventive Nephrology (N18.9)" --slug="kidney-health" || true
$WP_CLI term create sno10_condition "Bereavement & Craft Continuity" --slug="craft-bereavement" || true

echo "👤 Creating Author..."
$WP_CLI user create phil phil@pocketgull.com --role=author --display_name="Phil" || true

echo "📰 Setting Permalinks structure to /%postname%/..."
$WP_CLI rewrite structure '/%postname%/' --hard

echo "✨ WordPress Provisioning Complete! Site is live at $SITE_URL"
