# PocketGull Curie Luminescence Alacritty Theme
[colors.primary]
background = "#0f1416"
foreground = "#e2f8ee"

[colors.cursor]
text = "#0f1416"
cursor = "#00ff66"

[colors.selection]
text = "#e2f8ee"
background = "#00ff662b"

[colors.normal]
black = "#0a0e10"
red = "#ef4444"
green = "#00ff66"
yellow = "#84cc16"
blue = "#38bdf8"
magenta = "#c084fc"
cyan = "#2dd4bf"
white = "#e2f8ee"

[colors.bright]
black = "#475569"
red = "#f87171"
green = "#4ade80"
yellow = "#facc15"
blue = "#60a5fa"
magenta = "#d8b4fe"
cyan = "#5eead4"
white = "#ffffff"
