# PocketGull Hypertext 1991 Alacritty Theme
[colors.primary]
background = "#ffffff"
foreground = "#000000"

[colors.cursor]
text = "#ffffff"
cursor = "#000080"

[colors.selection]
text = "#000000"
background = "#b4d5fe"

[colors.normal]
black = "#000000"
red = "#800000"
green = "#008000"
yellow = "#808000"
blue = "#000080"
magenta = "#800080"
cyan = "#008080"
white = "#cccccc"

[colors.bright]
black = "#666666"
red = "#ff0000"
green = "#00aa00"
yellow = "#aaaa00"
blue = "#0000ff"
magenta = "#aa00aa"
cyan = "#008888"
white = "#ffffff"
