# PocketGull Rams Functionalist Alacritty Theme
[colors.primary]
background = "#f4f4f0"
foreground = "#1e1e1e"

[colors.cursor]
text = "#f4f4f0"
cursor = "#ea580c"

[colors.selection]
text = "#1e1e1e"
background = "#ea580c2a"

[colors.normal]
black = "#1e1e1e"
red = "#dc2626"
green = "#15803d"
yellow = "#ea580c"
blue = "#0284c7"
magenta = "#7e22ce"
cyan = "#0891b2"
white = "#d4d4cd"

[colors.bright]
black = "#52525b"
red = "#ef4444"
green = "#16a34a"
yellow = "#f59e0b"
blue = "#38bdf8"
magenta = "#9333ea"
cyan = "#06b6d4"
white = "#ffffff"
