name: "Dependency Review"

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'package*.json'
      - '**/package*.json'
      - '**/requirements*.txt'
      - '**/go.mod'
      - '**/go.sum'

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review & Vulnerability Gate
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Dependency Review
        continue-on-error: true
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v4.5.0
        with:
          fail-on-severity: critical
          comment-summary-in-pr: always
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, BlueOak-1.0.0, PSF-2.0, 0BSD, Unlicense, MPL-2.0, CC-BY-4.0, CC0-1.0, Python-2.0, AFL-2.1, AFL-3.0, MITNFA, Public Domain, LicenseRef-scancode-public-domain
          allow-dependencies-licenses: |
            pkg:pypi/fhir.resources, pkg:pypi/h5py, pkg:pypi/pandas, pkg:npm/isexe, pkg:npm/argparse, pkg:npm/bowser, pkg:npm/esprima, pkg:npm/import-in-the-middle, pkg:npm/json-schema, pkg:npm/lodash-es, pkg:npm/lodash.mapvalues, pkg:npm/uglify-js, pkg:npm/uri-templates, pkg:npm/@aws-sdk/types, pkg:npm/%40aws-sdk/types
